### ISSUE TITLE
Search service rewrite

### ISSUE THREAD

**Issue by pkpio** [praveendath92/coursestats#7]
It's a mess in there right now. Would be nice to rewrite this thing elegantly using promises. 

@giri7io , I think you are the best person for this.

**Comment by giri3sg** [comment]
yeah dude i will do that today

**Comment by pkpio** [comment]
That would be great! We can redo the layout after this. It is looking like a mess right now. One thing breaking other.

**Comment by pkpio** [comment]
Resolved.
